name: 🚀 Deploy do site para prod
on:
  push:
    branches:
      - main
jobs:
  deploy-develop:
    name: 🎉 Deploy para prod
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Baixar código-fonte
        uses: actions/checkout@v2

      # - name: 🚚 Instalar dependências
      #   run: composer install --verbose

      - name: 📂 Configurar PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: 📂 Deploy para prod
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          local-dir: "./"
          server-dir: "./"
          server: ftp.drytelecom.com.br
          username: ${{ secrets.FTP_USER_PRODUCTION }}
          password: ${{ secrets.FTP_PASSWORD_PRODUCTION }}
